#!/bin/bash
set -euo pipefail

# Initialize Boundary with scopes, host catalogs, and targets for devenv
# This script guides you through setting up Boundary to access devenv pods

NAMESPACE="${1:-boundary}"
DEVENV_NAMESPACE="${2:-devenv}"

echo "=========================================="
echo "  Boundary Initialization Guide"
echo "=========================================="
echo ""

# Check for boundary CLI
if ! command -v boundary &> /dev/null; then
    echo "⚠️  Boundary CLI not found"
    echo ""
    echo "Install it from: https://developer.hashicorp.com/boundary/downloads"
    echo ""
    echo "Or use Homebrew:"
    echo "  brew install hashicorp/tap/boundary"
    echo ""
fi

# Check for kubectl
if ! command -v kubectl &> /dev/null; then
    echo "❌ kubectl is required but not installed"
    exit 1
fi

echo "Step 1: Port Forward to Boundary Controller"
echo "--------------------------------------------"
echo ""
echo "In a separate terminal, run:"
echo "  kubectl port-forward -n $NAMESPACE svc/boundary-controller-api 9200:9200"
echo ""
read -p "Press Enter when port-forward is running..."

echo ""
echo "Step 2: Get Initial Admin Credentials"
echo "--------------------------------------"
echo ""
echo "Check the controller logs for initial credentials:"
echo ""
kubectl logs -n "$NAMESPACE" -l app=boundary-controller --tail=50 | grep -A5 "Initial" || echo "No initial credentials found in recent logs"

echo ""
echo "If this is a fresh install, look for output like:"
echo "  Initial auth information:"
echo "    Login Name: admin"
echo "    Password: <generated-password>"
echo "    Auth Method ID: ampw_..."
echo ""

echo ""
echo "Step 3: Authenticate with Boundary"
echo "-----------------------------------"
echo ""
echo "Using the credentials from Step 2:"
echo ""
echo "  export BOUNDARY_ADDR=http://127.0.0.1:9200"
echo "  boundary authenticate password \\"
echo "    -auth-method-id=<auth-method-id> \\"
echo "    -login-name=admin \\"
echo "    -password=<password>"
echo ""

echo ""
echo "Step 4: Create Organization and Project"
echo "----------------------------------------"
echo ""
echo "# Create org scope"
echo "boundary scopes create -name='DevOps' -description='DevOps Team' -scope-id=global"
echo ""
echo "# Note the org scope ID (o_...) and create project"
echo "boundary scopes create -name='Development' -description='Dev Environments' -scope-id=<org-id>"
echo ""

echo ""
echo "Step 5: Create Host Catalog for DevEnv"
echo "---------------------------------------"
echo ""
echo "# Get the devenv service ClusterIP"
DEVENV_IP=$(kubectl get svc devenv -n "$DEVENV_NAMESPACE" -o jsonpath='{.spec.clusterIP}' 2>/dev/null || echo "<devenv-service-ip>")
echo "DevEnv Service IP: $DEVENV_IP"
echo ""
echo "# Create static host catalog"
echo "boundary host-catalogs create static \\"
echo "  -name='devenv-hosts' \\"
echo "  -description='DevEnv Kubernetes Pods' \\"
echo "  -scope-id=<project-id>"
echo ""
echo "# Create host entry"
echo "boundary hosts create static \\"
echo "  -name='devenv-service' \\"
echo "  -address='$DEVENV_IP' \\"
echo "  -host-catalog-id=<host-catalog-id>"
echo ""
echo "# Create host set"
echo "boundary host-sets create static \\"
echo "  -name='devenv-set' \\"
echo "  -host-catalog-id=<host-catalog-id>"
echo ""
echo "# Add host to set"
echo "boundary host-sets add-hosts \\"
echo "  -id=<host-set-id> \\"
echo "  -host=<host-id>"
echo ""

echo ""
echo "Step 6: Create SSH Target"
echo "--------------------------"
echo ""
echo "# Create target for SSH access"
echo "boundary targets create tcp \\"
echo "  -name='devenv-ssh' \\"
echo "  -description='SSH to DevEnv pods' \\"
echo "  -default-port=22 \\"
echo "  -scope-id=<project-id>"
echo ""
echo "# Add host set to target"
echo "boundary targets add-host-sources \\"
echo "  -id=<target-id> \\"
echo "  -host-source=<host-set-id>"
echo ""

echo ""
echo "Step 7: Connect via Boundary"
echo "-----------------------------"
echo ""
echo "# Authorize a session"
echo "boundary connect ssh -target-id=<target-id> -- -l node"
echo ""
echo "# Or just get connection info"
echo "boundary connect -target-id=<target-id>"
echo ""

echo ""
echo "=========================================="
echo "  Quick Reference"
echo "=========================================="
echo ""
echo "Environment Variables:"
echo "  export BOUNDARY_ADDR=http://127.0.0.1:9200"
echo ""
echo "Useful Commands:"
echo "  boundary scopes list                    # List scopes"
echo "  boundary host-catalogs list -scope-id=X # List catalogs"
echo "  boundary targets list -scope-id=X       # List targets"
echo "  boundary sessions list                  # List active sessions"
echo ""
echo "DevEnv Service Info:"
kubectl get svc -n "$DEVENV_NAMESPACE" 2>/dev/null || echo "  (devenv namespace not found)"
echo ""
